---
version: "2.1"
services:
#
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: webtop
    privileged: true #optional
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUBFOLDER=/ #optional
    volumes:
      - ${LOCVOL1}webtop-xfce:/config
      - ${LOCVOL1}:/appdata
      #- /var/run/docker.sock:/var/run/docker.sock # We don't need direct docker access
    #ports:
      #- 3000:3000
    shm_size: "2gb" #optional
    restart: unless-stopped
#
#
networks:
  default:
    external:
      name: ${CONNET}
